version: "3"
services:
  plex:
    image: plexinc/pms-docker:plexpass
    network_mode: host
    environment:
      PUID: 1000
      PGID: 1000
      VERSION: latest
    volumes:
      - ./downloads:/downloads

  qbittorrent:
    image: linuxserver/qbittorrent
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ./qbittorrent/config:/config
      - ./downloads/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881

  sonarr:
    image: linuxserver/sonarr
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ./sonarr:/config
      - ./downloads:/downloads
    ports:
      - 8989:8989

  bazarr:
    image: linuxserver/bazarr
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - /path/to/bazarr/config:/config
      - /path/to/tvshows:/tv
      - /path/to/movies:/movies
    ports:
      - 6767:6767