version: "3"
services:
  plex:
    image: plexinc/pms-docker:plexpass
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
    volumes:
      - /path/to/plexconfig:/config
      - /path/to/plextranscode:/transcode
      - /path/to/media:/data
  
  qbittorrent:
    image: linuxserver/qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /path/to/qbittorrent/config:/config
      - /path/to/qbittorrent/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
  
  sonarr:
    image: linuxserver/sonarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /path/to/sonarr/config:/config
      - /path/to/tvshows:/tv
      - /path/to/qbittorrent/downloads:/downloads
    ports:
      - 8989:8989
  
  bazarr:
    image: linuxserver/bazarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /path/to/bazarr/config:/config
      - /path/to/tvshows:/tv
      - /path/to/movies